import "/Users/ajdanelz/Code/static-site-multiversion/examples/vuepress/node_modules/@vuepress/highlighter-helper/dist/client/styles/base.css"
import "/Users/ajdanelz/Code/static-site-multiversion/examples/vuepress/node_modules/@vuepress/plugin-prismjs/dist/client/styles/nord.css"
import "/Users/ajdanelz/Code/static-site-multiversion/examples/vuepress/node_modules/@vuepress/highlighter-helper/dist/client/styles/line-numbers.css"
import "/Users/ajdanelz/Code/static-site-multiversion/examples/vuepress/node_modules/@vuepress/highlighter-helper/dist/client/styles/notation-highlight.css"
import "/Users/ajdanelz/Code/static-site-multiversion/examples/vuepress/node_modules/@vuepress/highlighter-helper/dist/client/styles/code-block-title.css"